/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class Administratable extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): Administratable;
  methods: {
    addAdmin(adminToAdd: string): TransactionObject<void>;

    administrators(arg0: string): TransactionObject<boolean>;

    isAdministrator(addressToTest: string): TransactionObject<boolean>;

    owner(): TransactionObject<string>;

    removeAdmin(adminToRemove: string): TransactionObject<void>;

    renounceOwnership(): TransactionObject<void>;

    transferOwnership(newOwner: string): TransactionObject<void>;
  };
  events: {
    AdminAdded: ContractEvent<{
      addedAdmin: string;
      addedBy: string;
      0: string;
      1: string;
    }>;
    AdminRemoved: ContractEvent<{
      removedAdmin: string;
      removedBy: string;
      0: string;
      1: string;
    }>;
    OwnershipTransferred: ContractEvent<{
      previousOwner: string;
      newOwner: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
