/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class ChainlinkProxy extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): ChainlinkProxy;
  methods: {
    addAggregatorAddress(_a: string): TransactionObject<void>;

    aggregators(arg0: string): TransactionObject<boolean>;

    getDataPoint(
      _ref: string | number[]
    ): TransactionObject<{
      0: string;
      1: boolean;
    }>;

    getDataPointAtTime(
      _ref: string | number[],
      timestamp: number | string
    ): TransactionObject<string>;

    getLatestPrice(aggregator: string): TransactionObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
