/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class ERC20Interface extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): ERC20Interface;
  methods: {
    allowance(tokenOwner: string, spender: string): TransactionObject<string>;

    approve(
      spender: string,
      tokens: number | string
    ): TransactionObject<boolean>;

    balanceOf(tokenOwner: string): TransactionObject<string>;

    totalSupply(): TransactionObject<string>;

    transfer(to: string, tokens: number | string): TransactionObject<boolean>;

    transferFrom(
      from: string,
      to: string,
      tokens: number | string
    ): TransactionObject<boolean>;
  };
  events: {
    Approval: ContractEvent<{
      tokenOwner: string;
      spender: string;
      tokens: string;
      0: string;
      1: string;
      2: string;
    }>;
    Transfer: ContractEvent<{
      from: string;
      to: string;
      tokens: string;
      0: string;
      1: string;
      2: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
