/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class IOracleRegistry extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): IOracleRegistry;
  methods: {
    getDataPoint(
      _oracleProxy: string,
      _ref: string | number[]
    ): TransactionObject<{
      0: string;
      1: boolean;
    }>;

    registerOracle(_oracle: string): TransactionObject<void>;

    removeOracle(_oracle: string): TransactionObject<void>;

    setDataRegistry(_dataRegistry: string): TransactionObject<void>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
