/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class TestSignedMath extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): TestSignedMath;
  methods: {
    _floatDiv(
      a: number | string,
      b: number | string
    ): TransactionObject<string>;

    _floatMult(
      a: number | string,
      b: number | string
    ): TransactionObject<string>;

    _max(a: number | string, b: number | string): TransactionObject<string>;

    _min(a: number | string, b: number | string): TransactionObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
