/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class UniswapConfig extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): UniswapConfig;
  methods: {
    getTokenConfig(
      i: number | string
    ): TransactionObject<{
      cToken: string;
      underlying: string;
      symbolHash: string;
      baseUnit: string;
      priceSource: string;
      fixedPrice: string;
      uniswapMarket: string;
      isUniswapReversed: boolean;
    }>;

    getTokenConfigByCToken(
      cToken: string
    ): TransactionObject<{
      cToken: string;
      underlying: string;
      symbolHash: string;
      baseUnit: string;
      priceSource: string;
      fixedPrice: string;
      uniswapMarket: string;
      isUniswapReversed: boolean;
    }>;

    getTokenConfigBySymbol(
      symbol: string
    ): TransactionObject<{
      cToken: string;
      underlying: string;
      symbolHash: string;
      baseUnit: string;
      priceSource: string;
      fixedPrice: string;
      uniswapMarket: string;
      isUniswapReversed: boolean;
    }>;

    getTokenConfigBySymbolHash(
      symbolHash: string | number[]
    ): TransactionObject<{
      cToken: string;
      underlying: string;
      symbolHash: string;
      baseUnit: string;
      priceSource: string;
      fixedPrice: string;
      uniswapMarket: string;
      isUniswapReversed: boolean;
    }>;

    getTokenConfigByUnderlying(
      underlying: string
    ): TransactionObject<{
      cToken: string;
      underlying: string;
      symbolHash: string;
      baseUnit: string;
      priceSource: string;
      fixedPrice: string;
      uniswapMarket: string;
      isUniswapReversed: boolean;
    }>;

    maxTokens(): TransactionObject<string>;

    numTokens(): TransactionObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
