/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class DepositAllocaterStorage extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): DepositAllocaterStorage;
  methods: {
    deposits(
      arg0: string | number[]
    ): TransactionObject<{
      scheduledFor: string;
      amount: string;
      claimedAmount: string;
      totalAmountSignaled: string;
      token: string;
      onlySignaled: boolean;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: boolean;
    }>;

    totalAmountSignaledByHolder(arg0: string): TransactionObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
