/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class MarketObjectRegistry extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): MarketObjectRegistry;
  methods: {
    decodeCollateralObject(
      object: string | number[]
    ): TransactionObject<{
      0: string;
      1: BN;
    }>;

    encodeCollateralAsObject(
      collateralToken: string,
      collateralAmount: number | string
    ): TransactionObject<string>;

    renounceOwnership(): TransactionObject<void>;

    owner(): TransactionObject<string>;

    isOwner(): TransactionObject<boolean>;

    PRECISION(): TransactionObject<BN>;

    transferOwnership(newOwner: string): TransactionObject<void>;

    setMarketObjectProvider(
      marketObjectId: string | number[],
      provider: string
    ): TransactionObject<void>;

    publishDataPointOfMarketObject(
      marketObjectId: string | number[],
      timestamp: number | string,
      dataPoint: number | string
    ): TransactionObject<void>;

    getDataPointOfMarketObject(
      marketObjectId: string | number[],
      timestamp: number | string
    ): TransactionObject<{
      0: BN;
      1: boolean;
    }>;

    getMarketObjectLastUpdatedTimestamp(
      marketObjectId: string | number[]
    ): TransactionObject<BN>;
  };
  events: {
    UpdatedMarketObjectProvider: ContractEvent<{
      marketObjectId: string;
      provider: string;
      0: string;
      1: string;
    }>;
    PublishedDataPoint: ContractEvent<{
      marketObjectId: string;
      dataPoint: BN;
      0: string;
      1: BN;
    }>;
    OwnershipTransferred: ContractEvent<{
      previousOwner: string;
      newOwner: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
