/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class PaymentRegistry extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): PaymentRegistry;
  methods: {
    renounceOwnership(): TransactionObject<void>;

    owner(): TransactionObject<string>;

    isOwner(): TransactionObject<boolean>;

    transferOwnership(newOwner: string): TransactionObject<void>;

    paymentRouter(): TransactionObject<string>;

    setPaymentRouter(_paymentRouter: string): TransactionObject<void>;

    registerPayment(
      assetId: string | number[],
      cashflowId: number | string,
      eventId: number | string,
      token: string,
      amount: number | string
    ): TransactionObject<void>;

    getPayoffBalance(
      assetId: string | number[],
      eventId: number | string
    ): TransactionObject<string>;

    getPayoff(
      assetId: string | number[],
      eventId: number | string
    ): TransactionObject<{
      0: string;
      1: string;
      2: string;
    }>;
  };
  events: {
    Paid: ContractEvent<{
      assetId: string;
      eventId: string;
      amount: string;
      0: string;
      1: string;
      2: string;
    }>;
    OwnershipTransferred: ContractEvent<{
      previousOwner: string;
      newOwner: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
