/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class SettlementToken extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): SettlementToken;
  methods: {
    acceptOwnership(): TransactionObject<void>;

    decimals(): TransactionObject<string>;

    name(): TransactionObject<string>;

    newOwner(): TransactionObject<string>;

    owner(): TransactionObject<string>;

    symbol(): TransactionObject<string>;

    transferOwnership(_newOwner: string): TransactionObject<void>;

    totalSupply(): TransactionObject<string>;

    balanceOf(tokenOwner: string): TransactionObject<string>;

    transfer(to: string, tokens: number | string): TransactionObject<boolean>;

    approve(
      spender: string,
      tokens: number | string
    ): TransactionObject<boolean>;

    transferFrom(
      from: string,
      to: string,
      tokens: number | string
    ): TransactionObject<boolean>;

    allowance(tokenOwner: string, spender: string): TransactionObject<string>;

    approveAndCall(
      spender: string,
      tokens: number | string,
      data: string | number[]
    ): TransactionObject<boolean>;

    drip(receiver: string, tokens: number | string): TransactionObject<void>;

    transferAnyERC20Token(
      tokenAddress: string,
      tokens: number | string
    ): TransactionObject<boolean>;
  };
  events: {
    Approval: ContractEvent<{
      tokenOwner: string;
      spender: string;
      tokens: string;
      0: string;
      1: string;
      2: string;
    }>;
    OwnershipTransferred: ContractEvent<{
      _from: string;
      _to: string;
      0: string;
      1: string;
    }>;
    Transfer: ContractEvent<{
      from: string;
      to: string;
      tokens: string;
      0: string;
      1: string;
      2: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
