/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class Whitelist extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): Whitelist;
  methods: {
    owner(): TransactionObject<string>;

    isWhitelisted(account: string): TransactionObject<boolean>;

    addToWhitelist(account: string): TransactionObject<void>;

    removeFromWhitelist(account: string): TransactionObject<void>;

    transferOwnership(newOwner: string): TransactionObject<void>;
  };
  events: {
    OwnershipTransferred: ContractEvent<{
      previousOwner: string;
      newOwner: string;
      0: string;
      1: string;
    }>;
    WhitelistAccountAdded: ContractEvent<{
      account: string;
      caller: string;
      0: string;
      1: string;
    }>;
    WhitelistAccountRemoved: ContractEvent<{
      account: string;
      caller: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
