/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class RuleMock extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): RuleMock;
  methods: {
    canReturnTransferRestrictionCode(
      _restrictionCode: number | string
    ): TransactionObject<boolean>;

    detectTransferRestriction(
      arg0: string,
      arg1: string,
      _amount: number | string
    ): TransactionObject<string>;

    isTransferValid(
      _from: string,
      _to: string,
      _amount: number | string
    ): TransactionObject<boolean>;

    messageForTransferRestriction(
      _restrictionCode: number | string
    ): TransactionObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
